name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Rob'
runs:
  using: "composite"
  steps:
    - uses: rajbos/github-action-composite-message@main
    
    - run: echo Goodbye ${{ inputs.who-to-greet }}.
      shell: bash
